### ISSUE TITLE
I saw that the version of visionOS is running in window mode. Is it possible to make it run in space through CompositorLayer?

### ISSUE THREAD

**Issue by random-yang** [jinleili/wgpu-in-app#12]

**Comment by jinleili** [comment]
[The Rust bindings for CompositorServices](https://github.com/madsmtm/objc2/issues/393#issuecomment-2194371297) need to be implemented first.

**Comment by random-yang** [comment]
I have figured out the dependency relationship here. Thank you for your reply.
